config/routes.rb
Goodpeople::Application.routes.draw do
  resources :orders, only: [:new, :create, :show]
  resources :queries, only: [:new, :create, :show]

  namespace :admin do
    get '/', to: 'panel#index'
    
    controller :sessions do
      get '/login', to: :new
      post '/login', to: :create
      delete '/logout', to: :destroy
    end
    
    resources :actors do
      resources :photos
      resources :videos
      
      member do
        put :avatar
      end
    end
    
    resources :orders, only: [:index]
    resources :queries, only: [:index]
  end

  resources :actors

  root to: 'main#index'

end

app/models/actor.rb
class Actor < ActiveRecord::Base
  attr_accessible :description, :is_published, :name, :price, :avatar_id
  
  validates :name, presence: true
  validates :price, presence: true, numericality: { only_integer: true, greater_than: 100 }
  
  has_many :photos, dependent: :destroy
  has_many :videos, dependent: :destroy
  
  scope :published, where(is_published: true)
  
  def avatar
    if avatar_id
      photos.find(avatar_id).image_url
    else
      "dummy.jpg"
    end
  end
  
  def has_videos?
    videos.count > 0
  end
  
  def self.latest
    #for caching
    order('updated_at').last
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  attr_accessible :actor_id, :comment, :event_date, :name, :phone
  
  validates :name, presence: true
  validates :phone, presence: true
  
  belongs_to :actor
  
  def self.ordered
    order('created_at DESC')
  end
  
  def self.latest
    ordered.first(10)
  end
  
  def self.page(page)
    ordered.paginate(page: page, per_page: 10)
  end
  
  def actor_name
    actor.name if actor
  end
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  attr_accessible :image
  
  mount_uploader :image, ImageUploader
  
  belongs_to :actor
end

app/models/query.rb
class Query < ActiveRecord::Base
  attr_accessible :comment, :name, :phone
  
  validates :name, presence: true
  validates :phone, presence: true
  
  def self.ordered
    order('created_at DESC')
  end
  
  def self.latest
    ordered.first(10)
  end
  
  def self.page(page)
    ordered.paginate(page: page, per_page: 10)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password, :password_confirmation
  
  has_secure_password
end

app/models/video.rb
class Video < ActiveRecord::Base
  attr_accessible :actor_id, :video_id
  
  belongs_to :actor
  
  def embed_code
    "<iframe src='http://youtube.com/embed/#{video_id}'></iframe>"
  end
end

app/controllers/actors_controller.rb
class ActorsController < ApplicationController
end

app/controllers/admin/actors_controller.rb
class Admin::ActorsController < Admin::ApplicationController
  def index
    @actors = Actor.all
  end

  def new
    @actor = Actor.new
  end

  def create
    @actor = Actor.new(params[:actor])
    if @actor.save
      redirect_to admin_actor_url(@actor), notice: "Ведущий добавлен"
    else
      render :new, notice: "Не получилось, бро"
    end
  end

  def edit
  end
  
  def show
    @actor = Actor.find(params[:id])
  end
  
  def update
  end

  def destroy
    @actor = Actor.find(params[:id])
    @actor.destroy
    redirect_to admin_actors_url, notice: "Ведущий удален"
  end
  
  def avatar
    @actor = Actor.find(params[:id])
    if @actor.update_attributes(avatar_id: params['photo_id'])
      redirect_to admin_actor_path(@actor), notice: 'ок'
    else
      redirect_to admin_actor_path(@actor), notice: 'не ок'
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    @actors = Actor.published.all
    @order = Order.new
    @query = Query.new
    @actors_grouped = @actors.in_groups_of(4,false)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def new
    @order = Order.new
  end
  
  def create
    @order = Order.new(params[:order])
    if @order.save
      OrderMailer.new_order(@order).deliver
      render partial: 'success', layout: false
    else
      @actors = Actor.all
      render partial: 'form', layout: false
    end
  end
  
  def show
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
end

app/controllers/queries_controller.rb
class QueriesController < ApplicationController
  def new
    @query = Query.new
  end
  
  def create
    @query = Query.new(params[:query])
    if @query.save
      QueryMailer.new_query(@query).deliver
      render partial: 'success', layout: false
    else
      render partial: 'form', layout: false, locals: { title: nil, submit_text: nil }
    end
  end
  
  def show
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
end

app/helpers/actors_helper.rb
module ActorsHelper
end

app/helpers/admin/actors_helper.rb
module Admin::ActorsHelper
end

app/helpers/admin/panel_helper.rb
module Admin::PanelHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/queries_helper.rb
module QueriesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/actors/_actor.html.erb
<div class="popup actor-big" data-width="50%" data-position="top" data-scroll="scroll" id="actor-<%= actor.id %>">
  <div class="col-1-to-3-quarters cf">
    <div>
      <%= image_tag actor.avatar, class: "compact" %>
    </div>
    <div>
      <%= content_tag :h3, actor.name, class: "pinky" %>
      <%= content_tag :p, actor.description %>
    </div>
  </div>
  <% if actor.photos.any? %>
    <div class="gallery">
      <ul class="items">
        <% actor.photos.each do |photo| %>
          <li class="item"><%= image_tag photo.image_url, class: "compact" %><div class="overlay"></div>
        <% end %>
      </ul>
    </div>
  <% end %>
  <% if actor.videos.any? %>
    <h4 class="pinky txt-center">Видео</h4>
    <div class="tv">
      <div class="slider">
        <ul class="slides">
          <% actor.videos.each do |video| %>
            <li class="slide"><%= video.embed_code.html_safe %>
          <% end %>
        </ul>
        <a class="arrow outer-arrow left">
          &lsaquo;
        </a>
        <a class="arrow outer-arrow right">
          &rsaquo;
        </a> 
      </div>
    </div>
  <% end %>
  <span class="close">&times;</span>
</div>

app/views/actors/_list.erb
<% @actors_grouped.each do |group| %>
  <div class="cf col-4 pdb">
    <% group.each do |actor| %>
      <div class="actor popup-button" data-for="#actor-<%= actor.id %>">
        <%= image_tag actor.avatar %>
        <%= content_tag :div, actor.name, class: 'name red-gradiented helper' %>
        <%= content_tag :div, actor.price, class: 'price red-gradiented helper' %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/actors/_list.html.erb
<% cache ['actors_list', Actor.latest] do %>
  <% @actors_grouped.each do |group| %>
    <div class="cf col-4 pdb">
      <% group.each do |actor| %>
        <div class="actor popup-button" data-for="#actor-<%= actor.id %>">
          <%= image_tag actor.avatar %>
          <%= content_tag :div, actor.name, class: 'name red-gradiented helper' %>
          <%= content_tag :div, actor.price, class: 'price red-gradiented helper' %>
        </div>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/admin/actors/_actor.html.erb
<tr id="<%= actor.id %>" class="actor">
  <td>
    <%= actor.id %>
  </td>
  <td>
    <%= link_to actor.name, admin_actor_path(actor) %>
  </td>
  <td>
    <%= actor.price %>
  </td>
  <td>
    <%= actor.is_published %>
  </td>
  <td>
    <%= button_to "Удалить", admin_actor_path(actor), method: :delete %>
  </td>
</tr>

app/views/admin/actors/_form.html.erb
<%= form_for [:admin, @actor] do |f| %>
  <%= f.label :name, "Имя" %>
  <%= f.text_field :name %>
  
  <%= f.label :price, "Цена" %>
  <%= f.text_field :price %>
  
  <%= f.label :description, "Описание" %>
  <%= f.text_area :description %>
  
  <%= f.label :is_published, "Видимый" %>
  <%= f.check_box :is_published %>
  
  <%= f.submit "Сохранить" %> 
<% end %>

app/views/admin/actors/edit.html.erb
<h1>Admin::Actors#edit</h1>
<p>Find me in app/views/admin/actors/edit.html.erb</p>

app/views/admin/actors/index.html.erb
<h1>Ведущие</h1>

<p>
  <%= link_to 'Добавить', new_admin_actor_path %>
</p>

<table class="table table-striped">
  <thead>
    <th>#</th>
    <th>Имя</th>
    <th>Цена</th>
    <th>Видимый</th>
    <th>Действия</th>
  </thead>
  <%= render @actors %>
</table>

app/views/admin/actors/new.html.erb
<h1>Добавьте ведущего</h1>

<%= render 'form' %>

<%= link_to "Все ведущие", admin_actors_path %>

app/views/admin/actors/show.html.erb
<h1><%= @actor.name %></h1>

<!-- nav-tabs -->
<ul class="nav nav-tabs">
  <li class="active"><a href="#photos" data-toggle="tab">Фото</a></li>
  <li><a href="#videos" data-toggle="tab">Видео</a></li>
</ul>

<!-- tabs content -->
<div class="tab-content">
  <div class="tab-pane active photos" id="photos">
    <%= render @actor.photos %>
    <div>
      <%= render(partial: 'admin/photos/form', locals: { actor: @actor }) %>
    </div>
  </div>
  <div class="tab-pane videos" id="videos">
    <%= render @actor.videos %>
    <div>
      <%= render(partial: 'admin/videos/form', locals: { actor: @actor }) %>
    </div>
  </div>
</div>